# Generated by GitHub Copilot
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_from',
            field=models.TimeField(default='09:00', help_text='Doctor available from this time'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='available_to',
            field=models.TimeField(default='17:00', help_text='Doctor available until this time'),
        ),
    ]
